"""
NRG Agent OS - Phase 0 doctrine constants, derived from the Fable 5 Phase 0 Master System Prompt.
These are fixed governance constraints. Do not reinterpret, soften, skip, or merge.
"""

MASTER_BUILD_LAW = (
    "NRG Agent OS must be built as a safe, inspectable, recoverable operating system "
    "before intelligent, autonomous, or feature-rich agent behaviour is built."
)

MASTER_BUILD_LAW_EXPANDED = (
    "Fable 5 must build NRG Agent OS as a safe, inspectable, recoverable operating system before it builds "
    "any intelligent, autonomous, or feature-rich agent behaviour. Safety, evidence, auditability, reversibility, "
    "and human control are higher priorities than speed, capability, convenience, automation, model intelligence, "
    "or impressive output. The OS must become safe before it becomes smart. The OS must become inspectable before "
    "it becomes autonomous. The OS must become recoverable before it becomes powerful. A useful action is not "
    "automatically an authorized action. A correct recommendation is not automatically permission. A validated "
    "finding is not automatically approval to repair."
)

LOCKED_BUILD_ORDER = [
    "Section 0: Master Build Law & Non-Negotiable Safety Rules",
    "Section 1: What Not To Build Yet",
    "Phase 0: Source Lock",
    "Phase 1: Kernel",
    "Phase 2: Memory",
    "Phase 3: Router",
    "Phase 4: Validation",
    "Phase 5: Audit/Event Log",
    "Phase 6: Worker Contracts",
    "Phase 7: Skill System",
    "Phase 8: Recovery Rails",
    "Phase 9: Operator Interface",
    "Phase 10: Controlled Live Operation",
    "Final Acceptance Tests",
    "Section 35: Final Review Checklist",
]

PHASE_SUMMARIES = [
    {"phase": "Phase 1: Kernel",
     "purpose": "Establish SAFE STATE, boot sequence, operating modes, hardcoded safety rules, registry validation, and active integrity tests.",
     "law": "The OS must become safe before it becomes smart.",
     "inputs": "Accepted Phase 0 artifact set; operator acceptance of the Phase 0 Completion Report.",
     "outputs": "SAFE STATE definition, boot sequence, operating modes, deny-by-default permission base, registry validation, integrity tests.",
     "forbidden_early": "No memory ingestion, no routing, no workers, no live mutation.",
     "exit_proof": "Kernel boots to SAFE STATE; readonly/deny-by-default verified; integrity tests pass.",
     "depends": "All later phases depend on Kernel law and SAFE STATE.",
     "skip_danger": "Authority without law: every later component would self-authorize.",
     "key_concepts": ["readonly by default", "deny-by-default permissions", "no destructive action by default", "no shell execution by default", "no network action by default unless allowed", "no credential display", "agent autonomy paused", "human approval required for state-changing actions", "registry is testimony, not law", "memory is evidence, not authority"]},
    {"phase": "Phase 2: Memory",
     "purpose": "Initialize memory as inert evidence.",
     "law": "The kernel may remember, but it must not obey memory.",
     "inputs": "Kernel SAFE STATE; memory index design.",
     "outputs": "Memory index, persistent/scratch/quarantine/audit/user-preference memory tiers, stale-memory detection, prompt-injection rejection.",
     "forbidden_early": "No memory-granted authority; no ingestion before index.",
     "exit_proof": "Memory tiers isolated; conflict preservation works; no authority path from memory.",
     "depends": "Router, Validation, and Workers rely on memory being evidence-only.",
     "skip_danger": "Memory poisoning becomes command injection.",
     "key_concepts": ["memory index before memory ingestion", "persistent memory", "scratch memory", "quarantine memory", "audit memory", "user preference memory", "conflict preservation", "stale memory detection", "prompt-injection rejection", "no memory-granted authority"]},
    {"phase": "Phase 3: Router",
     "purpose": "Route tasks by minimum safe authority.",
     "law": "The router is an airlock, not a talent scout.",
     "inputs": "Kernel permissions; memory evidence tiers.",
     "outputs": "Route lanes, mutation levels, data scopes, capability requirements, risk classes, reversibility checks.",
     "forbidden_early": "No routing to unbuilt workers; no capability leasing yet.",
     "exit_proof": "Tasks route to minimum-authority lanes; escalation requires operator approval.",
     "depends": "Validation, Workers, and Skills require router lanes.",
     "skip_danger": "Tasks acquire maximum authority by default.",
     "key_concepts": ["route lanes", "mutation level", "data scope", "required capability", "risk class", "input trust", "evidence strength", "agent contract match", "approval state", "reversibility", "runtime kernel state", "output requirement"]},
    {"phase": "Phase 4: Validation",
     "purpose": "Adversarially validate task output.",
     "law": "No executor validates its own work.",
     "inputs": "Router lanes; executor outputs.",
     "outputs": "Adversarial validator, trust verdicts (PASS_TRUSTED, PASS_WITH_LIMITS, FAIL_*, QUARANTINE_OUTPUT, ESCALATE_TO_USER).",
     "forbidden_early": "No validator rubber-stamping; no self-validation.",
     "exit_proof": "Validator independently fails planted bad output; kernel decides trust.",
     "depends": "Audit and Worker Contracts require validation verdicts.",
     "skip_danger": "Hallucinated success becomes recorded fact.",
     "key_concepts": ["executor is testimony", "validator is adversary", "kernel decides trust", "PASS_TRUSTED", "PASS_WITH_LIMITS", "FAIL_UNSUPPORTED", "FAIL_SCOPE_ESCAPE", "FAIL_SAFETY", "FAIL_HALLUCINATION", "QUARANTINE_OUTPUT", "ESCALATE_TO_USER"]},
    {"phase": "Phase 5: Audit/Event Log",
     "purpose": "Create a causal, append-only, hash-chained event ledger.",
     "law": "The audit log is the black box flight recorder, not a diary.",
     "inputs": "Kernel events; validation verdicts.",
     "outputs": "Append-only ledger, kernel audit broker, hash chain, event signatures, causal links, fail-closed tamper handling.",
     "forbidden_early": "No mutable logs; no gaps tolerated.",
     "exit_proof": "Hash chain verifies; tamper attempt fails closed.",
     "depends": "Worker Contracts, Recovery, and Live Operation require audit chains.",
     "skip_danger": "Actions become unprovable; forensics impossible.",
     "key_concepts": ["append-only event ledger", "kernel audit broker", "hash chain", "event signatures", "causal links", "task card to router to permission to tool to output to validation to promotion", "fail-closed on audit gap or tamper"]},
    {"phase": "Phase 6: Worker Contracts",
     "purpose": "Activate workers only through bounded leases.",
     "law": "A worker does not own capability. A worker borrows capability for one task, one boundary, one output, one audit chain.",
     "inputs": "Router lanes; validation; audit ledger.",
     "outputs": "Worker activation gate, bounded task cards, lease system, reader-class worker roles.",
     "forbidden_early": "No standing authority, no self-selected tasks, no persistent write permission.",
     "exit_proof": "Worker completes bounded task card with full audit chain; escalation attempts blocked.",
     "depends": "Skill System requires worker contracts.",
     "skip_danger": "Workers freelance in the filesystem with standing authority.",
     "key_concepts": ["no standing authority", "no self-selected tasks", "no broad folder access", "no persistent write permission", "worker activation gate", "source-reader", "registry-reader", "memory-index-reader", "audit-reader", "task-card-checker", "validator-runner", "report-writer"]},
    {"phase": "Phase 7: Skill System",
     "purpose": "Define Skills as reusable procedures without authority.",
     "law": "Skills are recipes, not authority.",
     "inputs": "Worker contracts; router; kernel permissions.",
     "outputs": "Skill registry of capability recipes bound to Task Card + Lane + Permission + Lease + Audit + Validation.",
     "forbidden_early": "No skill runs by itself; no skill-granted authority.",
     "exit_proof": "Skill execution blocked without full authority chain.",
     "depends": "Recovery and Live Operation reuse skills under leases.",
     "skip_danger": "Recipes become self-executing authority.",
     "key_concepts": ["a Skill cannot run by itself", "Task Card supplies reason", "Router supplies lane", "Kernel supplies permission", "Worker supplies hands", "Audit Ledger supplies receipt", "Validator checks result"]},
    {"phase": "Phase 8: Recovery Rails",
     "purpose": "Separate Emergency Halt from Restoration.",
     "law": "Emergency Halt can pull the power. Restoration must prove it deserves a single insulated tool.",
     "inputs": "Audit chains; validation; operator approval gates.",
     "outputs": "Halt mechanism (authority removal only), procedural restoration with evidence preservation, rollback proof, independent validation.",
     "forbidden_early": "No autonomous repair bot.",
     "exit_proof": "Halt removes authority without mutation; restoration requires full proof chain.",
     "depends": "Live Operation requires recovery rails.",
     "skip_danger": "Repair becomes uncontrolled mutation under stress.",
     "key_concepts": ["halt removes authority only", "restoration is procedural", "no autonomous repair bot", "evidence preservation", "recovery task card", "exact target boundary", "rollback proof", "independent validation", "operator approval"]},
    {"phase": "Phase 9: Operator Interface",
     "purpose": "Expose verified operational state and approval gates.",
     "law": "The UI is a command cockpit, not dashboard soup.",
     "inputs": "Verified kernel state; audit chain; approval gates.",
     "outputs": "Kernel State view, Task Queue, Approval Gates, Audit Chain, Capability Leases, Alerts/Recovery, Evidence Viewer.",
     "forbidden_early": "No fake health scores, no mock telemetry in production, no broad approve-all buttons, no UI bypass.",
     "exit_proof": "UI displays only verified state; approval gates enforce kernel chain.",
     "depends": "Controlled Live Operation requires operator visibility.",
     "skip_danger": "Decorative health hides real failure.",
     "key_concepts": ["Kernel State view", "Task Queue", "Approval Gates", "Audit Chain", "Capability Leases", "Alerts and Recovery", "Evidence Viewer", "no fake health scores", "no mock telemetry in production", "no broad approve-all buttons", "no UI bypass"]},
    {"phase": "Phase 10: Controlled Live Operation",
     "purpose": "Prove safe contact with reality.",
     "law": "Day One is Dry-Run-Only.",
     "inputs": "All prior phases proven.",
     "outputs": "Sanity Task 001: inspect Phase 0 governance artifacts, report only, full validate + audit chain.",
     "forbidden_early": "No target mutation, no repair, no cleanup, no migration, no shell execution, no service restart.",
     "exit_proof": "Dry-run task completes with full chain and zero mutation.",
     "depends": "Final Acceptance Tests follow.",
     "skip_danger": "First live contact mutates real project state.",
     "key_concepts": ["Sanity Task 001", "inspect Phase 0 governance artifacts", "no target mutation", "no repair", "no cleanup", "no migration", "no shell execution", "no service restart", "report only", "validate chain", "audit chain"]},
    {"phase": "Final Acceptance Tests",
     "purpose": "Prove the OS resists unsafe but useful requests.",
     "law": "The Kernel must receive a mixed-risk live request and downgrade it to the safest valid route.",
     "inputs": "Complete OS through Phase 10.",
     "outputs": "Graduation test evidence: mutation/repair/cleanup/restart/escalation blocked while safe readonly inspection completes.",
     "forbidden_early": "Not run before Phase 10 completes.",
     "exit_proof": "Mixed-risk request safely downgraded with full audit.",
     "depends": "Section 35 review follows.",
     "skip_danger": "The OS graduates without proving refusal capability.",
     "key_concepts": ["mixed-risk live request", "downgrade to safest valid route", "block mutation, repair, cleanup, restart, authority escalation", "complete safe readonly inspection"]},
    {"phase": "Section 35: Final Review Checklist",
     "purpose": "Block authority laundering through usefulness.",
     "law": "Doing the right thing through the wrong authority path is a build failure.",
     "inputs": "Final acceptance evidence.",
     "outputs": "Final review checklist verdict.",
     "forbidden_early": "Not run before Final Acceptance Tests.",
     "exit_proof": "Checklist passes; no authority laundering path exists.",
     "depends": "Terminal gate.",
     "skip_danger": "Useful-but-unauthorized behaviour is certified as correct.",
     "key_concepts": ["authority laundering", "usefulness is not authority", "wrong authority path is build failure"]},
]

SOURCE_PRIORITY_ORDER = [
    {"rank": 1, "label": "Current Master Build Law and the Phase 0 System Prompt"},
    {"rank": 2, "label": "Current operator instruction"},
    {"rank": 3, "label": "Phase 0 Source Lock control files"},
    {"rank": 4, "label": "Project Manifest"},
    {"rank": 5, "label": "Complete Build Architecture Archive"},
    {"rank": 6, "label": "End Of Source Conversation"},
    {"rank": 7, "label": "Source Intake Prompt"},
    {"rank": 8, "label": "Dashboard Information Pack Assessment"},
    {"rank": 9, "label": "NRG Agent OS Factory Pack"},
    {"rank": 10, "label": "Primary architecture drafts"},
    {"rank": 11, "label": "Process-correction files"},
    {"rank": 12, "label": "Concept design files"},
    {"rank": 13, "label": "Behavioural-biopsy files"},
    {"rank": 14, "label": "JARVIS or cinematic dashboard inspiration"},
    {"rank": 15, "label": "Early assistant drafts or speculative notes"},
]

PRIORITY_RESOLUTION_RULES = [
    "User corrections outrank assistant framing.",
    "Hard safety rules outrank convenience.",
    "Current verified source state outranks memory.",
    "Current direct instruction outranks old brainstorming.",
    "Kernel law outranks registry claims.",
    "Registry claims are testimony only.",
    "Memory is evidence only.",
    "Dashboard concepts are not backend truth.",
    "Earlier drafts are useful only where they still support the latest corrected intent.",
]

RESOLUTION_RULE = (
    "If any source conflicts with the current Master Build Law or the Phase 0-only restriction, "
    "the current Master Build Law wins. Contradictions are preserved as classified evidence, "
    "never silently resolved, merged, or deleted."
)

CONTRADICTION_CLASSIFICATIONS = [
    "LOCKED_DECISION", "CURRENT_BEST_TRUTH", "CONTESTED_EVIDENCE", "HISTORICAL_CONTEXT",
    "SUPERSEDED", "UNSAFE_OR_REJECTED", "UNKNOWN_NEEDS_VERIFICATION",
]

FORBIDDEN_ACTIONS_PHASE0 = [
    "build Kernel code", "build memory loaders", "build router logic", "build validation agents",
    "build audit ledger logic", "build workers", "build skills", "build recovery automation",
    "build UI (OS operator interface)", "build live operation", "modify live Hermes folders",
    "edit registry files", "edit memory files", "edit hooks", "edit crons", "run repair scripts",
    "run live automation", "delete files", "move files", "rename files", "migrate files",
    "overwrite files outside the approved Phase 0 artifact set", "restart services",
    "install packages", "execute shell commands for live mutation", "treat memory as authority",
    "treat registry as authority", "treat the assessment PDF as law", "treat JARVIS as architecture",
    "treat dashboard concepts as backend truth", "claim the OS is operational",
    "claim implementation has begun beyond Phase 0", "imply Phase 1 through Phase 10 are complete",
    "silently resolve contradictions", "invent missing source facts", "create extra prompt bundles",
    "produce alternate plans", "continue after the Completion Report",
]

LOCKED_DECISIONS = [
    {"id": "D-001", "statement": "SAFE_STATE before capability.", "reason": "The OS must become safe before it becomes smart.", "impact": "All phases gate on SAFE STATE.", "phase": "Phase 1", "status": "LOCKED"},
    {"id": "D-002", "statement": "OS must be safe, inspectable, recoverable before autonomous.", "reason": "Master Build Law.", "impact": "Build order is fixed; capability last.", "phase": "All", "status": "LOCKED"},
    {"id": "D-003", "statement": "Kernel is law.", "reason": "Single source of authority; everything else is evidence or testimony.", "impact": "No component may self-authorize.", "phase": "Phase 1", "status": "LOCKED"},
    {"id": "D-004", "statement": "Registry is testimony.", "reason": "Registry entries claim state; they do not grant authority.", "impact": "Registry validation required; no registry-granted permission.", "phase": "Phase 1", "status": "LOCKED"},
    {"id": "D-005", "statement": "Memory is evidence.", "reason": "The kernel may remember, but it must not obey memory.", "impact": "No memory-granted authority; quarantine and conflict preservation required.", "phase": "Phase 2", "status": "LOCKED"},
    {"id": "D-006", "statement": "Router is airlock.", "reason": "Route by minimum safe authority, not by talent.", "impact": "Lanes, mutation levels, and risk classes are mandatory.", "phase": "Phase 3", "status": "LOCKED"},
    {"id": "D-007", "statement": "Validator is adversarial.", "reason": "Friendly validation rubber-stamps failure.", "impact": "Validation is an attack on the output, not a review.", "phase": "Phase 4", "status": "LOCKED"},
    {"id": "D-008", "statement": "No executor validates itself.", "reason": "Self-validation launders hallucination into fact.", "impact": "Independent validation required for trust.", "phase": "Phase 4", "status": "LOCKED"},
    {"id": "D-009", "statement": "Audit is causal flight recorder.", "reason": "Append-only, hash-chained, causally linked; fail-closed on tamper.", "impact": "No unaudited authority chain.", "phase": "Phase 5", "status": "LOCKED"},
    {"id": "D-010", "statement": "Workers borrow capability through leases.", "reason": "No standing authority; one task, one boundary, one output, one audit chain.", "impact": "Worker activation gate mandatory.", "phase": "Phase 6", "status": "LOCKED"},
    {"id": "D-011", "statement": "Skills are recipes, not authority.", "reason": "A Skill cannot run without Task Card, Lane, Permission, Lease, Audit, Validation.", "impact": "No self-executing skills.", "phase": "Phase 7", "status": "LOCKED"},
    {"id": "D-012", "statement": "Emergency Halt removes authority only.", "reason": "Halt must never mutate state.", "impact": "Halt and Restoration are separate rails.", "phase": "Phase 8", "status": "LOCKED"},
    {"id": "D-013", "statement": "Restoration requires proof, validation, audit, rollback, and approval.", "reason": "Repair under stress is the most dangerous mutation.", "impact": "No autonomous repair bot.", "phase": "Phase 8", "status": "LOCKED"},
    {"id": "D-014", "statement": "Operator Interface displays verified state, not dashboard decoration.", "reason": "Decorative health hides real failure.", "impact": "No fake status lights, no mock telemetry as production truth.", "phase": "Phase 9", "status": "LOCKED"},
    {"id": "D-015", "statement": "Day One is Dry-Run-Only.", "reason": "First live contact must prove governance before touching real files.", "impact": "Sanity Task 001 inspects Phase 0 artifacts, report only.", "phase": "Phase 10", "status": "LOCKED"},
    {"id": "D-016", "statement": "Usefulness is not authority.", "reason": "The OS must resist authority laundering through usefulness.", "impact": "A useful finding, obvious fix, validator pass, recommendation, skill, or UI button is not permission.", "phase": "All", "status": "LOCKED"},
    {"id": "D-017", "statement": "JARVIS is inspiration only.", "reason": "JARVIS may inform UX feel; it must not become OS architecture.", "impact": "No memory-galaxy cloning, no dashboard-first build.", "phase": "Phase 9", "status": "LOCKED"},
    {"id": "D-018", "statement": "Hermes is runtime/operator inside OS.", "reason": "Hermes executes approved skills under router and permission; it does not govern.", "impact": "Hermes may not change prompts, permissions, router policy, memory promotion, hooks, crons, or architecture.", "phase": "Phase 6+", "status": "LOCKED"},
    {"id": "D-019", "statement": "Fable is architect/review gate.", "reason": "Fable designs and judges; it is not an uncontrolled runtime executor.", "impact": "Fable role bounded to architecture, standards, review, quality gate.", "phase": "All", "status": "LOCKED"},
    {"id": "D-020", "statement": "Workers execute bounded task cards only.", "reason": "Workers may not design the OS, invent architecture, expand scope, or claim completion without evidence.", "impact": "Task card boundary is the worker's entire world.", "phase": "Phase 6", "status": "LOCKED"},
    {"id": "D-021", "statement": "Source contradictions must be preserved.", "reason": "Contradictions are evidence to classify, not noise to hide.", "impact": "No smoothing, averaging, merging, or silent resolution.", "phase": "Phase 0", "status": "LOCKED"},
]

KNOWN_ISSUES = [
    {"id": "I-001", "description": "Feature creep: scope expansion beyond the locked build order.", "risk": "HIGH", "phase": "All", "status": "OPEN", "mitigation": "BUILD_ORDER.md gates; NEXT_ACTION.md points to one valid action only.", "blocks_phase1": False},
    {"id": "I-002", "description": "Premature Kernel implementation before Phase 0 acceptance.", "risk": "HIGH", "phase": "Phase 1", "status": "OPEN", "mitigation": "Operator acceptance gate; forbidden-actions list enforced.", "blocks_phase1": False},
    {"id": "I-003", "description": "Dashboard-first drift: building the cockpit before contracts exist.", "risk": "HIGH", "phase": "Phase 9", "status": "OPEN", "mitigation": "Phase 9 gated behind Phases 1-8; dashboard concepts classified as concept-only.", "blocks_phase1": False},
    {"id": "I-004", "description": "Hermes overreach: runtime self-governance or silent prompt/permission changes.", "risk": "HIGH", "phase": "Phase 6+", "status": "OPEN", "mitigation": "D-018 locked; Hermes proposals require kernel chain.", "blocks_phase1": False},
    {"id": "I-005", "description": "Worker self-escalation: workers expanding scope or claiming unverified completion.", "risk": "HIGH", "phase": "Phase 6", "status": "OPEN", "mitigation": "Bounded task cards; leases; independent validation.", "blocks_phase1": False},
    {"id": "I-006", "description": "Memory poisoning: injected or stale memory acquiring authority.", "risk": "HIGH", "phase": "Phase 2", "status": "OPEN", "mitigation": "Memory is evidence; quarantine tier; injection rejection.", "blocks_phase1": False},
    {"id": "I-007", "description": "Stale source material treated as current instruction.", "risk": "MEDIUM", "phase": "Phase 0", "status": "MITIGATED_BY_CLASSIFICATION", "mitigation": "Authority levels + SUPERSEDED classification in SOURCE_INDEX.md.", "blocks_phase1": False},
    {"id": "I-008", "description": "Registry authority laundering: registry entries treated as law.", "risk": "HIGH", "phase": "Phase 1", "status": "OPEN", "mitigation": "D-004: registry is testimony; kernel validates.", "blocks_phase1": False},
    {"id": "I-009", "description": "Validator rubber-stamping: validation becomes friendly review.", "risk": "HIGH", "phase": "Phase 4", "status": "OPEN", "mitigation": "Adversarial validation doctrine; planted-failure tests.", "blocks_phase1": False},
    {"id": "I-010", "description": "Audit log tampering or gaps.", "risk": "HIGH", "phase": "Phase 5", "status": "OPEN", "mitigation": "Hash chain; fail-closed on gap or tamper.", "blocks_phase1": False},
    {"id": "I-011", "description": "Live Hermes modification too early.", "risk": "HIGH", "phase": "Phase 0", "status": "CONTROLLED", "mitigation": "Phase 0 forbids touching live Hermes folders, hooks, crons, memory, registries.", "blocks_phase1": False},
    {"id": "I-012", "description": "Duplicate source files creating conflicting authority claims.", "risk": "MEDIUM", "phase": "Phase 0", "status": "MITIGATED_BY_CLASSIFICATION", "mitigation": "DUPLICATE_REFERENCE classification; SHA256 hashing.", "blocks_phase1": False},
    {"id": "I-013", "description": "Contradictory drafts silently merged into a clean-looking plan.", "risk": "HIGH", "phase": "Phase 0", "status": "CONTROLLED", "mitigation": "Contradiction register with preserved classifications; D-021.", "blocks_phase1": False},
    {"id": "I-014", "description": "False done claims: completion asserted without artifact evidence.", "risk": "HIGH", "phase": "All", "status": "OPEN", "mitigation": "Definition of Done checks; completion report requires artifact verification.", "blocks_phase1": False},
    {"id": "I-015", "description": "Context bloat: feeding the entire archive at once degrades control.", "risk": "MEDIUM", "phase": "Phase 0", "status": "MITIGATED_BY_CLASSIFICATION", "mitigation": "Control packet feed order; archive files marked do-not-feed-first.", "blocks_phase1": False},
    {"id": "I-016", "description": "Concept-only files becoming law (JARVIS, dashboard framework).", "risk": "HIGH", "phase": "All", "status": "MITIGATED_BY_CLASSIFICATION", "mitigation": "CONCEPT_ONLY authority level; D-017.", "blocks_phase1": False},
    {"id": "I-017", "description": "Usefulness becoming permission (authority laundering).", "risk": "HIGH", "phase": "All", "status": "OPEN", "mitigation": "D-016; Section 35 final review checklist.", "blocks_phase1": False},
    {"id": "I-018", "description": "Three bundle files were UNLISTED in the original operator handoff (Production-Ready Go Blueprint, Detailed System Architecture Blueprint, deep-research-report #2).", "risk": "MEDIUM", "phase": "Phase 0", "status": "RESOLVED_BY_CLASSIFICATION", "mitigation": "Deep-read performed per operator instruction; all three classified as CONCEPT (strategy drafts / duplicate lineage / generic reference) with reasons recorded in SOURCE_INDEX.md. None may authorize build decisions.", "blocks_phase1": False},
    {"id": "I-019", "description": "Worker Task Card Template displayed as 0 KB, raising suspicion of an empty or invalid control file.", "risk": "MEDIUM", "phase": "Phase 0", "status": "RESOLVED_VERIFIED", "mitigation": "File verified: 495 bytes of complete, valid task-card template content (SHA256 prefix cd0f798da6c74cf9). The 0 KB reading was a console display rounding defect, corrected. File is trusted control doctrine.", "blocks_phase1": False},
]

GLOSSARY = [
    ("NRG Agent OS", "A model-agnostic, local-first, full-stack agent operating system: the permanent control structure that governs agents, models, routing, memory, skills, validation, permissions, recovery, audit, and operator visibility. Models are replaceable engines; the OS is the asset."),
    ("Kernel", "The law-bearing control core (Phase 1). Sole source of authority. Establishes SAFE STATE, operating modes, permissions, and integrity tests. Not built during Phase 0."),
    ("SAFE STATE", "The kernel's mandatory boot condition: readonly by default, deny-by-default permissions, no destructive/shell/network action by default, autonomy paused, human approval required for state change."),
    ("Registry", "A structured record of components and claims. Registry is testimony, not law: entries claim state but grant no authority."),
    ("Memory", "Stored context and evidence. Memory is evidence, not authority: the kernel may remember but must not obey memory."),
    ("Persistent Memory", "Long-lived memory tier surviving sessions; evidence-only, subject to staleness detection."),
    ("Scratch Memory", "Ephemeral working memory for a single task or session; discarded or archived, never authoritative."),
    ("Quarantine Memory", "Isolation tier for suspicious, conflicting, or unverified memory items pending review."),
    ("Router", "The airlock (Phase 3) that assigns each task the minimum safe authority lane. Not a talent scout."),
    ("Task Card", "A bounded, explicit work order defining reason, scope, boundary, expected output, and verification gate for one task."),
    ("Lane", "A router-assigned execution path with fixed mutation level, data scope, capability set, and risk class."),
    ("Validator", "The adversarial checker (Phase 4) that attacks executor output. Independent from the executor by law."),
    ("Executor", "The agent or model that performs a task. Executor output is testimony until validated."),
    ("Audit Ledger", "Append-only, hash-chained, causally linked event record (Phase 5). The black box flight recorder."),
    ("Evidence Bundle", "The collected proof set for a task: inputs, outputs, logs, hashes, validation verdicts, and causal links."),
    ("Capability", "A specific permitted power (read a path, write a file, call a tool) that can be granted, scoped, and revoked."),
    ("Capability Lease", "A temporary, task-scoped grant of capability: one task, one boundary, one output, one audit chain."),
    ("Mutation Level", "Router-assigned classification of how much state a task may change (none/readonly through destructive)."),
    ("Approval Gate", "A mandatory human decision point before state-changing or high-risk action proceeds."),
    ("Recovery Rail", "The separated Halt/Restoration mechanism (Phase 8) governing failure response."),
    ("Emergency Halt", "Authority removal mechanism. Pulls the power; never mutates state."),
    ("Restoration", "Procedural repair requiring evidence preservation, recovery task card, rollback proof, independent validation, and operator approval."),
    ("Worker Contract", "The binding boundary definition for a worker: what it may read, write, produce, and how it is validated (Phase 6)."),
    ("Skill", "A reusable capability recipe (Phase 7). Skills are recipes, not authority; they cannot run without the full kernel chain."),
    ("Operator Interface", "The command cockpit (Phase 9) exposing verified state, task queue, approval gates, audit chain, and leases. Not dashboard soup."),
    ("Controlled Live Operation", "Phase 10: first contact with reality, Dry-Run-Only on Day One, starting with Sanity Task 001."),
    ("Trusted", "Verdict state: output or memory independently validated and accepted by the kernel."),
    ("Quarantined", "Verdict state: output or memory isolated pending verification; unusable as truth."),
    ("Rejected Critical", "Verdict state: output failed validation on safety or integrity grounds; must not be used."),
    ("Contested Evidence", "A claim contradicted by another source; preserved with both sides recorded, not merged."),
    ("Promotion", "The controlled elevation of a claim, memory, or output to trusted status through the kernel chain."),
    ("Authority Laundering", "Converting usefulness, obviousness, validation passes, or recommendations into de facto permission. Forbidden."),
    ("Source Lock", "Phase 0: the controlled preservation, classification, and contradiction-preserving indexing of all project sources before any operational system is built."),
]

ROLE_SPLIT = {
    "Fable 5": ["architect", "system designer", "prompt designer", "standards writer", "UX system designer", "task-card designer", "reviewer", "quality gate", "final architectural judge"],
    "Hermes": ["daily runtime/operator inside the OS", "executes approved skills", "follows router decisions", "obeys permission modes", "writes structured logs", "proposes lessons/memory/skills/automations", "reports repeated failures"],
    "Workers": ["Codex", "GPT 5.5", "Gemini Pro 3.5", "local models", "cloud models", "Ornith candidates", "future worker agents - bounded task cards only"],
    "JARVIS": ["inspiration only - grounded answers, source proof, action confirmation, voice, model hot-swap UX, memory capture, cinematic feel"],
}
